<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>1.1.3</Version>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <EnableHarmony>true</EnableHarmony>
        <EnableModDeploy>false</EnableModDeploy>
        <EnableModZip>false</EnableModZip>
        <ModFolderName>CrossModCompatibilityTokens</ModFolderName>
        <Title>CrossModCompatibilityTokens</Title>
        <Authors>Spiderbuttons</Authors>
        <PackageId>CrossModCompatibilityTokens</PackageId>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Newtonsoft.Json" Private="False">
            <HintPath>$(GamePath)/smapi-internal/Newtonsoft.Json.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
